### ISSUE TITLE
It's not working..... can help?

### ISSUE THREAD

**Issue by linear80** [safirex/WNovelArchiver#12]
![123](https://user-images.githubusercontent.com/118615684/202854213-b099b7bf-743f-4cc7-869d-ea1705988dc5.JPG)
I have installed python and input as instructed in the video.... but nothing happens

**Comment by safirex** [comment]
I can suggest 2 things, either you downloaded the project long ago (like 1 year ago or more) when it didn't work yet as shown in the video (in that case just redownload the project ).
just to be sure you can also check if at the end of the archive_updater.py file there is the following code: ( just open it with your default text editor )
`
if __name__ == '__main__':  
    check_env()
    parser()
`


or I would say there may be an issue with your python installation.
the command ` python archive_updater.py` is supposed to give this instead of nothing at all.
![image](https://user-images.githubusercontent.com/41478485/202860730-416ac7c4-e2cf-424c-9252-a8950461d3ed.png)

you can try to use `python --version` in the command terminal to see if it is installed as it should.
